"""Orchestrate the full Excel export: run every exporter in dependency order
and write an IMPORT_GUIDE.md describing how the user should upload the files
into Zoho Books."""
import datetime as _dt
import os

from migration.export import exporters


# (key, label, callable, depends_on_files_from)
PHASES = [
    ('chart_of_accounts', 'Chart of Accounts',
     exporters.export_chart_of_accounts, []),
    ('taxes', 'Taxes (reference)',
     exporters.export_taxes, []),
    ('contacts', 'Customers & Vendors',
     exporters.export_contacts, []),
    ('projects', 'Projects',
     exporters.export_projects, ['contacts']),
    ('moves', 'Invoices / Credit Notes / Bills / Vendor Credits / Journals',
     exporters.export_moves, ['chart_of_accounts', 'contacts', 'projects']),
    ('payments', 'Customer & Vendor Payments',
     exporters.export_payments, ['contacts', 'moves']),
    ('time_entries', 'Time Entries',
     exporters.export_time_entries, ['projects']),
]


def run(odoo, out_dir, chunk_size, logger, phases=None):
    if phases is None or 'all' in phases:
        selected = PHASES
    else:
        selected = [p for p in PHASES if p[0] in phases]
        unknown = set(phases) - {k for k, *_ in PHASES} - {'all'}
        if unknown:
            raise ValueError(f'Unknown export phase(s): {sorted(unknown)}')

    os.makedirs(out_dir, exist_ok=True)
    summary = {}
    for key, label, fn, _deps in selected:
        logger.info('--- export phase: %s ---', key)
        summary[key] = fn(odoo, out_dir, chunk_size, logger)

    _write_import_guide(out_dir, summary)
    return summary


def _write_import_guide(out_dir, summary):
    """Write IMPORT_GUIDE.md alongside the XLSX files. It describes upload
    order, which Zoho Books UI page each file goes into, and notes the
    foreign-key-by-name constraints."""
    today = _dt.date.today().isoformat()
    lines = [
        f'# Zoho Books Import Guide ({today})',
        '',
        'These files were generated by `python -m migration export` against',
        'your Odoo instance. Upload them in the order below — each phase',
        'depends on names registered by the previous phase.',
        '',
        '## Upload order',
        '',
    ]

    def _files(key):
        s = summary.get(key) or {}
        return s.get('files') or []

    def _section(num, title, key, where, notes):
        files = _files(key)
        lines.append(f'### {num}. {title}')
        lines.append('')
        lines.append(f'**In Zoho Books:** {where}')
        lines.append('')
        if not files:
            lines.append('*(no rows — nothing to upload)*')
            lines.append('')
            return
        for p in files:
            lines.append(f'- `{os.path.basename(p)}`')
        if notes:
            lines.append('')
            for n in notes:
                lines.append(f'> {n}')
        lines.append('')

    _section(
        1, 'Chart of Accounts', 'chart_of_accounts',
        'Accountant → Chart of Accounts → ⋯ → Import Chart of Accounts',
        [
            'Map columns to: Account Name, Account Code, Account Type, '
            'Description, Currency.',
            'Account Type values use Zoho\'s built-in enum (Income, Expense, '
            'Bank, Cash, Fixed Asset, Other Current Asset, '
            'Accounts Receivable, Accounts Payable, etc.).',
        ],
    )

    _section(
        2, 'Taxes (reference only — recreate manually)', 'taxes',
        'Settings → Taxes → + New Tax',
        [
            '**Zoho Books has no CSV importer for taxes.** Use this sheet '
            'as a list and create each tax in the UI before importing any '
            'invoices/bills that use it. Match the Tax Name exactly '
            '(e.g. `GST 5% [Odoo #21]`).',
        ],
    )

    _section(
        3, 'Customers', 'contacts',
        'Sales → Customers → ⋯ → Import Customers',
        [
            'Display Name is the unique key. Other tabs (invoices, etc.) '
            'will reference customers by Display Name.',
        ],
    )

    _section(
        4, 'Vendors', 'contacts',
        'Purchases → Vendors → ⋯ → Import Vendors',
        [],
    )

    _section(
        5, 'Projects', 'projects',
        'Time Tracking → Projects → ⋯ → Import Projects',
        [
            'Customer Name must match a Display Name from step 3.',
        ],
    )

    _section(
        6, 'Invoices', 'moves',
        'Sales → Invoices → ⋯ → Import Invoices',
        [
            'Upload `06_invoices_*.xlsx` files only (skip the credit_notes, '
            'bills, vendor_credits, manual_journals files for this step).',
            'Customer Name + Account + Item Tax must match names from '
            'previous steps.',
        ],
    )

    _section(
        7, 'Credit Notes', 'moves',
        'Sales → Credit Notes → ⋯ → Import Credit Notes',
        ['Upload `07_credit_notes_*.xlsx` files.'],
    )

    _section(
        8, 'Bills', 'moves',
        'Purchases → Bills → ⋯ → Import Bills',
        ['Upload `08_bills_*.xlsx` files. Vendor Name + Account must match.'],
    )

    _section(
        9, 'Vendor Credits', 'moves',
        'Purchases → Vendor Credits → ⋯ → Import Vendor Credits',
        ['Upload `09_vendor_credits_*.xlsx` files.'],
    )

    _section(
        10, 'Manual Journals', 'moves',
        'Accountant → Manual Journals → ⋯ → Import Manual Journals',
        [
            'Upload `10_manual_journals_*.xlsx` files. Multiple rows '
            'sharing the same Journal Number are treated as one journal.',
        ],
    )

    _section(
        11, 'Customer Payments', 'payments',
        'Sales → Payments Received → ⋯ → Import Payments',
        [
            'Upload `11_customer_payments_*.xlsx`. Invoice Number must '
            'match an invoice already imported in step 6.',
        ],
    )

    _section(
        12, 'Vendor Payments', 'payments',
        'Purchases → Payments Made → ⋯ → Import Payments Made',
        [
            'Upload `12_vendor_payments_*.xlsx`. Bill Number must match a '
            'bill imported in step 8.',
        ],
    )

    _section(
        13, 'Time Entries', 'time_entries',
        'Time Tracking → Time Entries → ⋯ → Import Time Entries',
        [
            'Project Name must match a project imported in step 5. '
            'Odoo employee name is preserved in the Description prefix '
            '(e.g. `[John Smith] Welded beam`) so per-employee reporting '
            'is still possible via the entry text.',
        ],
    )

    lines.extend([
        '## Foreign-key matching tips',
        '',
        'Zoho\'s importer matches references **by name, exactly**:',
        '- `Customer Name` on invoices must equal `Display Name` on a '
        'customer row.',
        '- `Account` on invoice line items must equal `Account Name` on a '
        'chart-of-accounts row.',
        '- `Item Tax` must equal a Tax Name you set up manually in Zoho.',
        '- Every Odoo id is preserved as a `[Odoo #N]` suffix so reruns are '
        'idempotent and matches are unambiguous.',
        '',
        '## What was skipped',
        '',
    ])
    self_pid = (summary.get('contacts') or {}).get('self_partner_skipped')
    if self_pid:
        lines.append(f'- res.partner #{self_pid} (your own company) and any '
                     f'transaction referencing it.')
    skipped_no_proj = (summary.get('time_entries') or {}).get(
        'skipped_no_project', 0)
    if skipped_no_proj:
        lines.append(f'- {skipped_no_proj} time entries with no resolvable '
                     f'project / cost center.')
    moves_skipped = ((summary.get('moves') or {}).get('counts') or {}).get(
        'skipped_self', 0)
    if moves_skipped:
        lines.append(f'- {moves_skipped} moves referencing the self-partner.')
    payments_skipped = ((summary.get('payments') or {}).get('counts') or {}).get(
        'skipped_self', 0)
    if payments_skipped:
        lines.append(f'- {payments_skipped} payments referencing the '
                     f'self-partner.')

    with open(os.path.join(out_dir, 'IMPORT_GUIDE.md'), 'w',
              encoding='utf-8') as f:
        f.write('\n'.join(lines).rstrip() + '\n')
